[project]
name = "cache22"
version = "0.0.1"
description = "CLI for archiving Git repositories into Fossil"
requires-python = ">=3.14"
dependencies = [
    "tomli-w>=1.2.0",
    "typer>=0.24.1",
]

[project.scripts]
cache22 = "cache22.cli:main"

[dependency-groups]
dev = [
    "check-jsonschema>=0.36.2",
    "pre-commit>=4.5.1",
    "pyright>=1.1.408",
    "pytest>=9.0.0",
    "ruff>=0.15.4",
    "yamllint>=1.38.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"
